name: Build and Push Custom Image

on:
  push:
    paths:
      - 'version.txt'
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract digest from version.txt
        id: get-version
        run: |
          if [ -f "version.txt" ]; then
            DIGEST=$(grep -oP 'digest=\s*\K[^ ]+' version.txt)
            echo "BASE_DIGEST=$DIGEST" >> $GITHUB_ENV
            echo "IMAGE_TAG=${DIGEST:0:12}" >> $GITHUB_ENV
          else
            echo "version.txt 文件不存在"
            exit 1
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BASE_DIGEST=${{ env.BASE_DIGEST }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qinglong-selenium:latest
            ghcr.io/${{ github.repository_owner }}/qinglong-selenium:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send success notification
        if: success()
        run: |
          echo "镜像构建并推送成功!"