name: Build and Push Custom Image

on:
  push:
    paths:
      - 'version.txt'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract digest from version.txt
        id: get-version
        run: |
          DIGEST=$(grep -oP 'digest=\s*\K[^ ]+' version.txt)
          echo "BASE_DIGEST=$DIGEST" >> $GITHUB_ENV
          echo "IMAGE_TAG=${DIGEST:0:12}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BASE_DIGEST=${{ env.BASE_DIGEST }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update deployment manifest (可选)
        if: success()
        run: |
          # 如果有 Kubernetes 部署文件，可以在这里更新镜像标签
          # 例如使用 sed 或 yq 替换部署文件中的镜像标签
          echo "构建完成，可以在此步骤更新部署配置"