name: Check Base Image Updates and Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 检查
  workflow_dispatch:      # 支持手动触发

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current digest from registry
        id: get-digest
        run: |
          # 获取 GHCR token
          TOKEN=$(curl -s "https://ghcr.io/token?scope=repository:whyour/qinglong:pull&service=ghcr.io" | jq -r .token)
          
          # 获取镜像 manifest 并计算 digest
          DIGEST=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/whyour/qinglong/manifests/debian" | shasum -a 256 | cut -d ' ' -f1)
          
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT

      - name: Compare and update version.txt
        id: update-version
        run: |
          # 检查 version.txt 是否存在并读取当前 digest
          if [ -f "version.txt" ]; then
            CURRENT_DIGEST=$(grep -oP 'digest=\s*\K[^ ]+' version.txt || echo "")
          else
            CURRENT_DIGEST=""
          fi
          
          NEW_DIGEST="${{ steps.get-digest.outputs.DIGEST }}"
          
          if [ "$CURRENT_DIGEST" != "$NEW_DIGEST" ]; then
            echo "发现新版本! 更新 version.txt"
            echo "digest=$NEW_DIGEST" > version.txt
            
            # 配置 Git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # 提交更改
            git add version.txt
            git commit -m "chore: 更新基础镜像 digest 为 $NEW_DIGEST"
            
            # 使用 GITHUB_TOKEN 推送
            git push
            
            # 设置标志表示需要构建
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "BASE_DIGEST=$NEW_DIGEST" >> $GITHUB_ENV
            echo "IMAGE_TAG=${NEW_DIGEST:0:12}" >> $GITHUB_ENV
          else
            echo "镜像未更新"
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        if: steps.update-version.outputs.should_build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BASE_DIGEST=${{ env.BASE_DIGEST }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qinglong-with-chrome:latest
            ghcr.io/${{ github.repository_owner }}/qinglong-with-chrome:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send notification
        if: always()
        run: |
          if [ "${{ steps.update-version.outputs.should_build }}" = "true" ]; then
            echo "镜像已更新并构建成功!"
            # 可以添加通知代码，如 Slack、Discord 或邮件
          else
            echo "镜像未更新，无需构建"
          fi