name: Check Base Image Updates

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 检查
  workflow_dispatch:      # 支持手动触发

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Get current digest from registry
        id: get-digest
        run: |
          # 获取 GHCR token
          TOKEN=$(curl -s "https://ghcr.io/token?scope=repository:whyour/qinglong:pull&service=ghcr.io" | jq -r .token)
          
          # 获取镜像 manifest 并计算 digest
          DIGEST=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/whyour/qinglong/manifests/debian" | shasum -a 256 | cut -d ' ' -f1)
          
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT

      - name: Compare and update version.txt
        id: update-version
        run: |
          # 检查 version.txt 是否存在并读取当前 digest
          if [ -f "version.txt" ]; then
            CURRENT_DIGEST=$(grep -oP 'digest=\s*\K[^ ]+' version.txt || echo "")
          else
            CURRENT_DIGEST=""
          fi
          
          NEW_DIGEST="${{ steps.get-digest.outputs.DIGEST }}"
          
          if [ "$CURRENT_DIGEST" != "$NEW_DIGEST" ]; then
            echo "发现新版本! 更新 version.txt"
            echo "digest=$NEW_DIGEST" > version.txt
            
            # 配置 Git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # 提交更改
            git add version.txt
            git commit -m "chore: 更新基础镜像 digest 为 $NEW_DIGEST"
            
            # 使用 PAT 推送
            git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
            
            # 设置标志表示需要触发构建
            echo "should_trigger_build=true" >> $GITHUB_OUTPUT
          else
            echo "镜像未更新"
            echo "should_trigger_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build workflow via API
        if: steps.update-version.outputs.should_trigger_build == 'true'
        run: |
          # 等待几秒确保推送完成
          sleep 10
          
          # 使用 API 触发构建工作流
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-push.yml/dispatches \
            -d '{"ref":"main"}'